"""empty message

Revision ID: 3e52dc307343
Revises: d8e8c181c813
Create Date: 2023-08-14 02:29:05.472399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e52dc307343'
down_revision = 'd8e8c181c813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sizes', ['size_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_order_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')
        batch_op.drop_column('paypal_order_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('size_id')

    # ### end Alembic commands ###
