"""empty message

Revision ID: 51c1b2f49dcc
Revises: 796a0985a5f5
Create Date: 2023-08-17 04:01:27.398535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c1b2f49dcc'
down_revision = '796a0985a5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
