"""empty message

Revision ID: 76b681d508e5
Revises: 1a647cd83dbf
Create Date: 2023-08-13 22:50:33.921504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b681d508e5'
down_revision = '1a647cd83dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
